spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_database
spring.datasource.username=postgres
spring.datasource.password=${PSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret-key=${JWT_SECRET_KEY}
scheduler.revoked-tokens.cron=0 */15 * * * ?
scheduler.enabled=true