spring.application.name=notification-service

notifications.queue=notificationToSendQueue

spring.datasource.url=jdbc:postgresql://localhost:5432/notifications_db
spring.datasource.username=notifications_service
spring.datasource.password=devpass

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml

#spring.jpa.hibernate.ddl-auto=validate

bean-definitions.processors.processorsBeans.EMAIL=emailNotificationProcessor
bean-definitions.processors.processorsBeans.SMS=smsNotificationProcessor
bean-definitions.processors.processorsBeans.DEFAULT=emailNotificationProcessor