spring.application.name=notification-service
rabbitmq.queue=notificationToSendQueue
rabbitmq.exchange=notificationToSendExchange
rabbitmq.routing=notification.to.send.#

spring.datasource.url=jdbc:postgresql://localhost:5432/notifications_db
spring.datasource.username=notifications_service
spring.datasource.password=devpass

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate

bean-definitions.processorsBeans=emailNotificationProcessor
bean-definitions.defaultProcessorBean=emailNotificationProcessor