spring.application.name=policy-service

spring.datasource.url=jdbc:postgresql://localhost:5433/policy_db
spring.datasource.username=policy_service
spring.datasource.password=devpass

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
